### ISSUE TITLE
Warning line 36

### ISSUE THREAD

**Issue by th1460** [spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex#1]
When I run the example, show me a warning (line 36) "LaTeX Font Warning: Font shape `T1/ClearSans-LF/m/sc' undefined".

**Comment by spagnuolocarmine** [comment]
It is possible that depends on your LaTex configuration.... could you add more details?

**Comment by th1460** [comment]
Updated my texmaker. Work now! Thanks
