### ISSUE TITLE
How to change 'cvname' font size ?

### ISSUE THREAD

**Issue by jay-thakur** [spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex#11]
Hi, 
I am using predefined "cvname" element to write name but its a little bit larger and crossing the profile region(left side region). I am using like this.
`\cvname{MY Name Here}`

How to change 'cvname' font size ?

**Comment by AtefBN** [comment]
Hello Jay, you can change that in the twentysecondcv.cls file, line #174
https://github.com/spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex/blob/master/twentysecondcv.cls#L174, you can change Huge into:
\huge
\LARGE
\Large
\large
\normalsize (default)
\small
\footnotesize
\scriptsize
\tiny
cheers

**Comment by spagnuolocarmine** [comment]
You can also add the font size to the `\cvname` macro. 
For instance:
`\cvname{\Large Alice}`

The default value is \Huge, please consider that if you change the font size the pagination is your business.

Thank you for this issue.

Sorry for the long time delay :-)
