### ISSUE TITLE
Add Logos to TwentyItem

### ISSUE THREAD

**Issue by jpps2408** [spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex#12]
Hey! Thanks for the great work! I'm building my resume and a nice addition would be to be able to add logos (of the university, company, etc.) to each item, do you think you can do it?

**Comment by spagnuolocarmine** [comment]
I added the support to Icon in both sections and twenty items.
Thank you for your suggestions!

Enjoy.

- Support Fontawesome Icons new class option ```\documentclass[icon]{twentysecondcv}```, using the name of the icon available in the documentation of the package [here](https://github.com/spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex/raw/master/fontawesome.pdf).
- The Fontawesome version requires the Fontawesome installed. Notice that the  Fontawesome is already available in Overleaf.com.
- Section with Icon:
```
\sectionicon{icon-name}{section-name}
```
- Twenty icon items environment
```
\begin{twentyicon}
  \twentyitemicon
    {icon name}
    {year}
    {title}
    {place}
    {description}
\end{twentyicon}
```
- Twenty items icon short environment
```
\begin{twentyshorticon}
  \twentyitemshorticon
    {icon name}
    {year}
    {description}
\end{twentyshorticon}
```
