### ISSUE TITLE
Change the name of the blocks

### ISSUE THREAD

**Issue by tbgd** [spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex#3]
Hi, 

I was wondering if you could provide me with some help on how to change the names of the different blocks ("About Me", "Skills", etc,...). I was hoping to adapt them a bit more to my resume.

Thank you, 
Thibault GERARD

**Comment by spagnuolocarmine** [comment]
Please open an issue on GitHub and I can answer on Github for all community.

thks

Cheers
ᐧ

2017-11-14 15:42 GMT+01:00 tbgd <notifications@github.com>:

**Comment by spagnuolocarmine** [comment]
Ok it is already an issue sorry!

thks
ᐧ

2017-11-14 15:49 GMT+01:00 Carmine Spagnuolo <spagnuolocarmine@gmail.com>:

**Comment by spagnuolocarmine** [comment]
Change the words in this file https://github.com/spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex/blob/master/twentysecondcv.cls

We have to update the style to be configurable the blocks...
