### ISSUE TITLE
Make picture optional

### ISSUE THREAD

**Issue by baco** [spagnuolocarmine/TwentySecondsCurriculumVitae-LaTex#8]
Sometimes it is required to send a CV without picture, age, gender or nationality to avoid disqualification by discrimination.

So it would be useful to have the possibility to avoid putting the picture field when building the profile. Currently, LaTeX rises an error when the `\profilepic` command is not used.

**Comment by spagnuolocarmine** [comment]
I made it optional. Thank you for your suggestion.
I apologize for the super long delay :)
